services:
  - type: web
    name: llm-feedback-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gmail_feedback_watcher.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
