services:
  - type: web
    name: LLM-Feedack-Serivce
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python pdf_service.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
